FundConnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('branch/', include('branch.urls'), name='branch'),
    path('member/', include('member.urls'), name='member'),
    path('accounts/', include('accounts.urls'), name='accounts'),
]

accounts/urls.py
# @Project:     FundConnect
# @Filename:    urls.py
# @Author:      Daksh Gaur
# @Email:       hi@daksh.fyi
# @Time:        24-06-2023 03:40 pm
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='cashbook-home'),
    path('create/', views.create_cashbook_entry, name='cashbook-create'),
    path('search/', views.search_cashbook, name='cashbook-search'),
    path('<int:pk>/<str:financial_year>/cashbook/', views.view_cashbook, name='cashbook-view'),
    path('transactions/', views.search_transactions, name='transactions-search'),
    path('<str:year>/<str:month>/<str:date>/transactions/', views.transaction_by_date, name='transactions-view'),
    path('all/', views.view_all_cashbook, name='cashbook-all'),
    path('branch/', views.create_branch_entry, name='branch-cashbook-create'),
    path('branch/<int:date>/<int:month>/<int:year>/', views.list_branch_for_entry, name='cashbook-branches-list'),
    path('branch/<int:pk>/<int:date>/<int:month>/<int:year>/', views.create_entry_for_selected_branch,
         name='cashbook-entry-selected-branch'),
    path('apply-for-loan/', views.loan_application, name='loan-apply'),
]

core/urls.py
# @Project:     FundConnect
# @Filename:    urls.py
# @Author:      Daksh
# @Time:        08-06-2023 12:38 pm

from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('dev-guide/', views.dev_guide, name='dev-guide'),
]

accounts/models.py
from django.db import models
from member.models import Member
from django.core.validators import RegexValidator
from dashboard.models import Controller
from .calculations import helper_functions


class Cashbook(models.Model):
    financial_year_validator = RegexValidator(
        regex=r'^\d{4}-\d{2}$',
        message="Financial year must be in the format 'YYYY-YY'"
    )

    financial_year = models.CharField(
        max_length=7,
        validators=[financial_year_validator]
    )
    member = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='cashbooks')

    def __str__(self):
        return f"{self.financial_year} - {self.member.id} {self.member.name}"


class CashBookEntry(models.Model):
    FUND_TYPES = [
        ('OPENING BALANCE', 'Opening_Balance'),
        ('CLOSING BALANCE', 'Closing_Balance'),
        ('INTEREST', 'Interest'),
        ('DIVIDEND', 'Dividend'),
        ('SALARY', 'Salary'),
        ('DEPOSIT', 'Deposit'),
        ('ADJUSTMENT', 'Adjustment'),
        ('CHEQUE', 'Cheque'),
        ('SERVICE_FEE', 'Service Fee'),
        ('OTHER', 'Other'),
        ('LOAN', 'Loan'),
        ('SHARES', 'Shares'),
    ]

    date = models.IntegerField()
    month = models.IntegerField()
    year = models.IntegerField()
    fund_type = models.CharField(max_length=20, choices=FUND_TYPES)
    refund_on_exit_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    deposits_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    loan_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    shares_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    cashbook = models.ForeignKey(Cashbook, on_delete=models.CASCADE, related_name='entries')
    remittance_posted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.date}-{self.month}-{self.year}: {self.fund_type}, {self.member.id} {self.member.name}"

    def save(self, *args, **kwargs):
        # Automatically determine the cashbook based on the financial year
        financial_year = helper_functions.get_financial_year(self.month, self.year)

        cashbook, created = Cashbook.objects.get_or_create(
            financial_year=financial_year,
            member=self.member
        )

        if self.fund_type not in ['OPENING BALANCE', 'CLOSING BALANCE', 'LOAN', 'SHARES']:
            self.member.refund_on_exit += self.refund_on_exit_amount
            self.member.deposits += self.deposits_amount
            self.member.loan += self.loan_amount
            self.member.share_holding += self.shares_amount
            self.member.save()

        self.cashbook = cashbook
        super().save(*args, **kwargs)


class Loan(models.Model):
    date = models.IntegerField()
    month = models.IntegerField()
    year = models.IntegerField()
    ask_loan_amount = models.DecimalField(max_digits=10, decimal_places=2)
    allotted_loan_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    allotted_to_member = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='loans')
    number_of_installments = models.IntegerField(default=120)

accounts/forms.py
# @Project:     FundConnect
# @Filename:    forms.py
# @Author:      Daksh Gaur
# @Email:       hi@daksh.fyi
# @Time:        24-06-2023 03:28 pm
from django import forms
from .models import CashBookEntry, Loan

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'
SEARCH_INPUT_CLASSES = 'w-full py-2 px-4 border'


class CashBookEntryForm(forms.ModelForm):
    class Meta:
        model = CashBookEntry
        fields = (
            'date', 'month', 'year', 'fund_type', 'refund_on_exit_amount', 'deposits_amount', 'loan_amount', 'member',
        )
        widgets = {
            'date': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'month': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'year': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'fund_type': forms.Select(attrs={'class': INPUT_CLASSES}),
            'refund_on_exit_amount': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'deposits_amount': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'loan_amount': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'member': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
        }


class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = (
            'date', 'month', 'year', 'ask_loan_amount', 'allotted_to_member', 'number_of_installments'
        )
        widgets = {
            'date': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'month': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'year': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'ask_loan_amount': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'allotted_to_member': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'number_of_installments': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
        }

accounts/views.py
# views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .forms import CashBookEntryForm, LoanForm
from .models import CashBookEntry, Cashbook
from branch.models import Branch
from dashboard.models import Controller
from member.models import Member
from django.db.models import Q, F, ExpressionWrapper, IntegerField, Prefetch
from .calculations import loan_emi, interest, apply_loan, helper_functions
from django.contrib import messages


def home(request):
    return render(request, 'accounts/cashbook-home.html')


# Save to database
def create_cashbook_entry(request):
    if request.method == 'POST':
        form = CashBookEntryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:cashbook-home')
    else:
        form = CashBookEntryForm()

    return render(request, 'accounts/create-entry.html', {'form': form})


def view_cashbook(request, pk, financial_year):
    # sorting the cashbook entries by year and month (From April to March)
    cashbook_entries = CashBookEntry.objects.filter(
        member__id=pk,
        cashbook__financial_year=financial_year
    ).annotate(
        year_month_expression=ExpressionWrapper(
            # Custom expression to sort the cashbook entries by year and month of the financial year
            # (From April to March)
            # For example, 03 2024 will be 202403, and 05 2023 will be 202304
            F('year') * 100 + F('month'),
            output_field=IntegerField()
        )
    ).order_by('year_month_expression')

    member = member = get_object_or_404(Member, id=pk)

    context = {
        'cashbook_entries': cashbook_entries,
        'member_id': pk,
        'financial_year': financial_year,
        'member': member,
    }
    return render(request, 'accounts/cashbook-view.html', context)


def view_all_cashbook(request):
    if request.method == 'POST':
        financial_year = request.POST.get('financial_year')
        cashbooks = Cashbook.objects.filter(financial_year=financial_year)

        cashbook_entries = CashBookEntry.objects.filter(
            cashbook__financial_year=financial_year
        ).select_related('cashbook', 'member').prefetch_related(
            Prefetch('member__cashbooks', queryset=Cashbook.objects.filter(financial_year=financial_year))
        ).annotate(
            year_month_expression=ExpressionWrapper(
                # Custom expression to sort the cashbook entries by year and month of the financial year
                # (From April to March)
                # For example, 03 2024 will be 202403, and 05 2023 will be 202304
                F('year') * 100 + F('month'),
                output_field=IntegerField()
            )
        ).order_by('year_month_expression')

        context = {
            'cashbooks': cashbooks,
            'financial_year': financial_year,
            'cashbook_entries': cashbook_entries,
        }

        return render(request, 'accounts/cashbook-all-members.html', context)

    return render(request, 'accounts/cashbook-all-search.html')


def search_cashbook(request):
    if request.method == 'POST':
        member_id = request.POST.get('member_id')
        financial_year = request.POST.get('financial_year')

        # Redirect to the cashbook entry list URL with the member ID and financial year as parameters
        return redirect(reverse('accounts:cashbook-view', kwargs={'pk': member_id, 'financial_year': financial_year}))
    else:
        return render(request, 'accounts/cashbook-search.html')


def transaction_by_date(request, date, month, year):
    if int(month) == 0:
        cashbook_entries = CashBookEntry.objects.filter(
            year=year,
        )
    elif int(date) == 0:
        cashbook_entries = CashBookEntry.objects.filter(
            year=year,
            month=month
        )
    else:
        cashbook_entries = CashBookEntry.objects.filter(
            year=year,
            month=month,
            date=date
        )

    context = {
        'cashbook_entries': cashbook_entries,
        'date': date,
        'month': month,
        'year': year,
    }

    return render(request, 'accounts/transaction-by-date.html', context)


def search_transactions(request):
    if request.method == 'POST':
        date = request.POST.get('date')
        month = request.POST.get('month')
        year = request.POST.get('year')

        return redirect(reverse('accounts:transactions-view', kwargs={'year': year, 'month': month, 'date': date}))
    else:
        return render(request, 'accounts/transaction-search.html')


def loan_application(request):
    if request.method == 'POST':
        form = LoanForm(request.POST)
        if form.is_valid():
            loan = form.save(commit=False)
            controller = Controller.objects.all().first()
            if apply_loan.check_eligibility(loan.allotted_to_member, controller, loan):
                apply_loan.allot_shares(loan.allotted_to_member, controller, loan)
                loan.save()
                return redirect('core:home')
            else:
                messages.error(request, "Loan eligibility check failed.")
        else:
            messages.error(request, "Invalid form submission.")
    else:
        form = LoanForm()

    return render(request, 'accounts/loan-application.html', {'form': form})


def create_branch_entry(request):
    if request.method == 'POST':
        date = request.POST.get('date')
        month = request.POST.get('month')
        year = request.POST.get('year')

        # branches = Branch.objects.all()
        # controller = Controller.objects.all().first()
        # members = Member.objects.all()
        # members = members.filter(active_user=True)

        return redirect(reverse('accounts:cashbook-branches-list', kwargs={'year': year, 'month': month, 'date': date}))
    else:
        return render(request, 'accounts/branch-remittance-entry-create.html')


def list_branch_for_entry(request, date, month, year):
    branches = Branch.objects.all()
    branches = branches.filter(members__isnull=False).distinct()
    controller = Controller.objects.all().first()
    members = Member.objects.all()
    members = members.filter(active_user=True)

    financial_year = helper_functions.get_financial_year(month, year)
    branch_remittance_posted = {}
    for branch in branches:
        if Member.objects.filter(branch_id=branch.id).exists():
            # Retrieve the first member's cashbook
            member = Member.objects.filter(branch_id=branch.id).first()
            cashbook_entry = CashBookEntry.objects.filter(
                member__id=member.id,
                cashbook__financial_year=financial_year
            ).filter(date=date, month=month, year=year).first()
            if cashbook_entry is None:
                branch_remittance_posted[branch.id] = False
            else:
                branch_remittance_posted[branch.id] = bool(cashbook_entry.remittance_posted)
    context = {
        'branches': branches,
        'controller': controller,
        'members': members,
        'date': date,
        'month': month,
        'year': year,
        'branch_remittance_posted': branch_remittance_posted,
    }
    return render(request, 'accounts/branch-remittance-entry-list.html', context)


# TODO: interest calculations, MARCH entry, CLOSING BALANCE entry, DIVIDEND entry
def create_entry_for_selected_branch(request, pk, date, month, year):
    branch = get_object_or_404(Branch, id=pk)
    controller = Controller.objects.all().first()
    members = Member.objects.filter(branch=branch)
    members = members.filter(active_user=True)

    # Create a cashbook entry for each member of the branch
    for member in members:

        # if the month is April
        if month == 4:

            # Opening balance Entry
            # not meant to be saved in the database
            cashbook_entry = CashBookEntry(
                member=member,
                date=1,
                month=4,
                year=year,
                fund_type='OPENING BALANCE',
                refund_on_exit_amount=member.refund_on_exit,
                deposits_amount=member.deposits,
                loan_amount=member.loan,

            )
            cashbook_entry.save()

            # April month entry
            emi = loan_emi.calculate_loan_emi(0, 0, 0)

            cashbook_entry = CashBookEntry(
                member=member,
                date=date,
                month=month,
                year=year,
                fund_type='SALARY',
                refund_on_exit_amount=controller.refund_on_exit_monthly_deposit,
                deposits_amount=member.wish_to_deposit,
                loan_amount=emi,
                remittance_posted=True,
            )

            cashbook_entry.save()

        # if the month is March
        elif month == 3:
            # month entry
            # refund on exit interest entry
            # deposit interest entry
            # dividend entry
            # Closing balance Entry
            pass
        else:

            # loan emi
            emi = loan_emi.calculate_loan_emi(0, 0, 0)

            cashbook_entry = CashBookEntry(
                member=member,
                date=date,
                month=month,
                year=year,
                fund_type='SALARY',
                refund_on_exit_amount=controller.refund_on_exit_monthly_deposit,
                deposits_amount=member.wish_to_deposit,
                loan_amount=emi,
                remittance_posted=True,
            )

            cashbook_entry.save()

    # Log success message
    branch_name = branch.name
    success_message = f"Successfully posted for {branch_name}"
    messages.success(request, success_message, extra_tags="success")

    return redirect(reverse('accounts:cashbook-branches-list', kwargs={'year': year, 'month': month, 'date': date}))

accounts/templates/accounts/branch-remittance-entry-create.html
<!-- cashbook_entry_search.html -->
{% extends 'core/base.html' %}

{% block title %}Create Entry{% endblock %}
{% block heading %}Enter Date for entry{% endblock %}

{% block content %}
    <div class="max-w-full mx-auto bg-gray-200 p-6 rounded-lg shadow-lg">
        <form method="post" action=".">
            {% csrf_token %}

            <div class="flex flex-wrap -mx-4">
                <div class="w-full md:w-1/3 px-4 mb-4">
                    <label for="date" class="font-bold">Date</label>
                    <input type="text" name="date" id="date" class="w-full py-4 px-6 rounded-xl border" required>
                </div>

                <div class="w-full md:w-1/3 px-4 mb-4">
                    <label for="month" class="font-bold">Month</label>
                    <input type="text" name="month" id="month" class="w-full py-4 px-6 rounded-xl border" required>
                </div>

                <div class="w-full md:w-1/3 px-4 mb-4">
                    <label for="year" class="font-bold">Year</label>
                    <input type="text" name="year" id="year" class="w-full py-4 px-6 rounded-xl border" required>
                </div>
            </div>

            <div class="flex justify-end mt-6">
                <button class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded">Search</button>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/branch-remittance-entry-list.html
{% extends 'core/base.html' %}
{% load custom_filters %}

{% block title %}Entry for Branch{% endblock %}
{% block heading %}Entry for Branch for {{ date }}-{{ month }}-{{ year }}{% endblock %}
{% if messages %}
    {% block notification %}
        <div id="sticky-message-container"
             class="fixed inset-x-0 flex items-center justify-center z-1 ">
            <div class="bg-green-500 text-white rounded font-bold text-center py-2 px-4">
                {% for message in messages %}
                    <div class="mb-2">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        </div>

        <script>
            setTimeout(function () {
                var stickyMessageContainer = document.getElementById('sticky-message-container');
                stickyMessageContainer.remove();
            }, 1000);
        </script>
    {% endblock %}
{% endif %}

{% block content %}


    <div class="container mx-auto px-4 py-8 max-w-full mx-auto bg-gray-200 rounded-lg shadow-lg">
        <ul>
            <table class="w-full border-collapse">
                <colgroup>
                    <col style="width: 45%;">
                    <col style="width: 45%;">
                    <col style="width: 10%;">
                </colgroup>
                <thead>
                <tr>
                    <th class="border-4 border-gray-500 px-4 py-2">Name</th>
                    <th class="border-4 border-gray-500 px-4 py-2">Location</th>
                    <th class="border-4 border-gray-500 px-4 py-2">Edit</th>
                </tr>
                </thead>
                <tbody>
                {% for branch in branches %}
                    {% if branch_remittance_posted|get_item:branch.id == False %}
                        <tr>
                            <td class="border border-gray-500 px-4 py-2">{{ branch.name }}</td>
                            <td class="border border-gray-500 px-4 py-2">{{ branch.location }}</td>
                            <td class="border border-gray-500 px-4 py-2">
                                <a href="{% url 'accounts:cashbook-entry-selected-branch' branch.id date month year %}"
                                   class="inline-block bg-blue-500 hover:bg-blue-700 text-white py-2 px-6 rounded">Post
                                    Remittance</a>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </ul>
    </div>
{% endblock %}

accounts/templates/accounts/cashbook-all-members.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/output.css" %}">
    <style>
        table {
            border-collapse: collapse;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
        }
    </style>
</head>
<body>
{% for cashbook in cashbooks %}
    {% if cashbook.member.active_user %}
        <div class="max-w-full mx-auto p-6 rounded-lg">
            <div class="flex justify-between mb-6">
                <div>
                    <h2 class="text-2xl font-semibold">{{ cashbook.member.name }}</h2>
                    <p class="text-gray-500">Membership No.: {{ cashbook.member.id }}</p>
                    <p class="text-gray-500">Branch: {{ cashbook.member.branch }}</p>
                </div>
                <div>
                    <h2 class="text-2xl font-semibold">Financial Year: {{ financial_year }}</h2>
                </div>
            </div>

            {% if cashbook_entries %}
                <table class="w-full mt-6">
                    <thead>
                    <tr>
                        <th>Date</th>
                        <th>Transaction Particulars</th>
                        <th>NRD Credit</th>
                        <th>NRD Debit</th>
                        <th>Deposits Credit</th>
                        <th>Deposits Debit</th>
                        <th>Loan Credit</th>
                        <th>Loan Debit</th>
                        <th>Shares Credit</th>
                        <th>Shares Debit</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for entry in cashbook_entries %}
                        {% if entry.cashbook.member.id == cashbook.member.id %}
                            <tr>
                                <td>{{ entry.date }}/{{ entry.month }}/{{ entry.year }}</td>
                                <td>{{ entry.fund_type }}</td>
                                {% if entry.refund_on_exit_amount > 0 %}
                                    <td>{{ entry.refund_on_exit_amount }}</td>
                                    <td>---</td>
                                {% elif entry.refund_on_exit_amount == 0 %}
                                    <td>---</td>
                                    <td>---</td>
                                {% else %}
                                    <td>---</td>
                                    <td>{{ entry.refund_on_exit_amount }}</td>
                                {% endif %}
                                {% if entry.deposits_amount > 0 %}
                                    <td>{{ entry.deposits_amount }}</td>
                                    <td>---</td>
                                {% elif entry.deposits_amount == 0 %}
                                    <td>---</td>
                                    <td>---</td>
                                {% else %}
                                    <td>---</td>
                                    <td>{{ entry.deposits_amount }}</td>
                                {% endif %}
                                {% if entry.loan_amount < 0 %}
                                    <td>{{ entry.loan_amount }}</td>
                                    <td>---</td>
                                {% elif entry.loan_amount == 0 %}
                                    <td>---</td>
                                    <td>---</td>
                                {% else %}
                                    <td>---</td>
                                    <td>{{ entry.loan_amount }}</td>
                                {% endif %}
                                {% if entry.shares_amount > 0 %}
                                    <td>{{ entry.shares_amount }}</td>
                                    <td>---</td>
                                {% elif entry.shares_amount == 0 %}
                                    <td>---</td>
                                    <td>---</td>
                                {% else %}
                                    <td>---</td>
                                    <td>{{ entry.shares_amount }}</td>
                                {% endif %}
                            </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No cashbook entries found.</p>
            {% endif %}
        </div>
        <br>
        <div class="flex justify-between mb-6">
            <div>
                <p class="px-6">TREASURER</p>
            </div>
            <div>
                <h2 class="px-6">HON. SECRETARY</h2>
            </div>
        </div>
        <br>
        <div class="py-4 px-6 text-sm text-bold">
            <p>NOTE :- IN CASE OF ANY DISCREPANCY, PLEASE POINT OUT THE SAME TO THE SOCIETY</p>
            <P>IN 15 DAYS, OTHERWISE IT WILL BE TREATED AS CORRECT AND FINAL</P>
        </div>

        <!-- Add a page break after each member's data -->
        <div style="page-break-after: always;"></div>
    {% endif %}
{% endfor %}
</body>
</html>

accounts/templates/accounts/cashbook-all-search.html
{% extends 'core/base.html' %}

{% block title %}All Cashbooks{% endblock %}
{% block heading %}Enter Financial Year{% endblock %}

{% block content %}
    <div class="max-w-full mx-auto bg-gray-200 p-6 rounded-lg shadow-lg">
        <form method="POST" action="." target="_blank">
            {% csrf_token %}
            <div class="mb-4">
                <label for="id_financial_year" class="font-bold">Financial Year (YYYY-YY)</label>
                <input type="" name="financial_year" id="id_financial_year" class="w-full py-4 px-6 rounded-xl border"
                       required>
            </div>
            <button class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded">Generate</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/cashbook-home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Manage Funds{% endblock %}
{% block heading %}Manage Funds{% endblock %}
{% block content %}
    <div class="flex justify-center items-center">
        <div class="space-y-4 container mx-auto px-4 py-8 max-w-xl mx-auto bg-gray-200 rounded-lg shadow-lg">
            <div class="flex flex-col space-y-4">
                <div class="flex flex-row space-x-4">
                    <a href="{% url 'accounts:loan-apply' %}" class="btn btn-blue">
                        Loan Application
                    </a>
                    <a href="{% url 'accounts:cashbook-create' %}" class="btn btn-yellow">
                        Create a entry
                    </a>
                    <a href="{% url "accounts:cashbook-search" %}" class="btn btn-red">
                        View Member's CashBook
                    </a>
                </div>
                <a href="{% url "accounts:transactions-search" %}" class=" btn btn-gray">
                    Search for transactions
                </a>
                <a href="{% url "accounts:cashbook-all" %}" class="btn btn-green">
                    Annual Financial Statement of all the members
                </a>
                <a href="#" class="btn btn-purple">
                    Unassigned
                </a>
            </div>
        </div>
    </div>
    <style>
        .btn {
            display: inline-block;
            padding: 0.75rem 1.5rem;
            font-weight: bold;
            text-align: center;
            text-decoration: none;
            border-radius: 0.375rem;
            transition: all 0.3s ease;
        }

        .btn-blue {
            background-color: #3B82F6;
            color: #FFFFFF;
        }

        .btn-yellow {
            background-color: #F59E0B;
            color: #FFFFFF;
        }

        .btn-red {
            background-color: #EF4444;
            color: #FFFFFF;
        }

        .btn-green {
            background-color: #10B981;
            color: #FFFFFF;
        }

        .btn-purple {
            background-color: #8B5CF6;
            color: #FFFFFF;
        }

        .btn-gray {
            background-color: #9CA3AF;
            color: #FFFFFF;
        }

        .btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.15);
        }
    </style>
{% endblock %}

accounts/templates/accounts/cashbook-search.html
<!-- cashbook_entry_search.html -->
{% extends 'core/base.html' %}

{% block title %}Ledger Entry Search{% endblock %}
{% block heading %}Ledger Entry Search{% endblock %}

{% block content %}
    <div class="max-w-full mx-auto bg-gray-200 p-6 rounded-lg shadow-lg">
        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-4">
                <label for="member_id" class="font-bold">Membership No.</label>
                <input type="text" name="member_id" id="member_id" class="w-full py-4 px-6 rounded-xl border" required>
            </div>

            <div class="mb-4">
                <label for="financial_year" class="font-bold">Financial Year (Format: 20YY-YY)</label>
                <input type="text" name="financial_year" id="financial_year" class="w-full py-4 px-6 rounded-xl border"
                       required>
            </div>

            <div class="flex justify-end mt-6">
                <button class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded">Search</button>
            </div>
        </form>
    </div>
{% endblock %}