FundConnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('branch/', include('branch.urls'), name='branch'),
    path('member/', include('member.urls'), name='member'),
    path('accounts/', include('accounts.urls'), name='accounts'),
]

accounts/urls.py
# @Project:     FundConnect
# @Filename:    urls.py
# @Author:      Daksh Gaur
# @Email:       hi@daksh.fyi
# @Time:        24-06-2023 03:40 pm
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='cashbook-home'),
    path('create/', views.create_cashbook_entry, name='cashbook-create'),
    path('search/', views.search_cashbook, name='cashbook-search'),
    path('<int:pk>/<str:financial_year>/cashbook/', views.view_cashbook, name='cashbook-view'),
    path('transactions/', views.search_transactions, name='transactions-search'),
    path('<str:year>/<str:month>/<str:date>/transactions/', views.transaction_by_date, name='transactions-view'),
    path('all/', views.view_all_cashbook, name='cashbook-all'),
    path('branch/', views.create_branch_entry, name='branch-cashbook-create'),
    path('branch/<int:date>/<int:month>/<int:year>/', views.list_branch_for_entry, name='cashbook-branches-list'),
    path('branch/<int:pk>/<int:date>/<int:month>/<int:year>/', views.create_entry_for_selected_branch,
         name='cashbook-entry-selected-branch'),
    path('apply-for-loan/', views.loan_application, name='loan-apply'),
]

core/urls.py
# @Project:     FundConnect
# @Filename:    urls.py
# @Author:      Daksh
# @Time:        08-06-2023 12:38 pm

from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('dev-guide/', views.dev_guide, name='dev-guide'),
]

member/urls.py
# @Project:     FundConnect
# @Filename:    urls.py
# @Author:      Daksh
# @Time:        08-06-2023 01:09 pm
from django.urls import path
from . import views

app_name = 'member'

urlpatterns = [
    path('', views.home, name='member-home'),
    path('create/', views.create_member, name='member-create'),
    path('edit/', views.member_edit_search_view, name='member-edit'),
    path('<int:pk>/edit/', views.edit_selected_member, name='member-edit-pk'),
    path('remove/', views.remove_member, name='member-remove'),
    path('<int:pk>/remove/', views.remove_selected_member, name='member-remove-pk'),
    path('list/', views.view_member, name='member-view'),
    path('<int:pk>/view/', views.view_selected_member, name='member-view-pk'),
    path('ex-members/', views.terminated_members, name='member-terminated'),
]

member/models.py
from django.db import models
from branch.models import Branch


# Create your models here.
class Member(models.Model):
    id = models.IntegerField(primary_key=True)  # Membership number
    name = models.CharField(max_length=100)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name='members')
    position = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary = models.DecimalField(max_digits=10, decimal_places=2)
    wish_to_deposit = models.DecimalField(max_digits=10, decimal_places=2, default=100)
    refund_on_exit = models.DecimalField(max_digits=10, decimal_places=2)
    deposits = models.DecimalField(max_digits=10, decimal_places=2)
    loan = models.DecimalField(max_digits=10, decimal_places=2)
    share_holding = models.DecimalField(max_digits=10, decimal_places=2)
    active_user = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.id} - {self.name}"

member/forms.py
# @Project:     FundConnect
# @Filename:    forms.py
# @Author:      Daksh
# @Time:        08-06-2023 01:27 pm
from django import forms
from .models import Member
from branch.models import Branch

# styling
# FORM_INPUT = 'w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-500'
# FORM_SELECT = 'w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-500'
# FORM_CHECKBOX = 'form-checkbox text-blue-500'
INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'
SEARCH_INPUT_CLASSES = 'w-full py-2 px-4 border'


class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = (
            'id', 'name', 'branch', 'position', 'monthly_salary', 'wish_to_deposit', 'refund_on_exit',
            'deposits',
            'loan',
            'share_holding')
        widgets = {
            'id': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'name': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'branch': forms.Select(attrs={'class': INPUT_CLASSES}),
            'position': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'monthly_salary': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'wish_to_deposit': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'refund_on_exit': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'deposits': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'loan': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'share_holding': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
        }


class EditMemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = (
            'id', 'name', 'branch', 'position', 'monthly_salary', 'wish_to_deposit', 'refund_on_exit',
            'deposits',
            'loan',
            'share_holding', 'active_user')
        widgets = {
            'id': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'name': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'branch': forms.Select(attrs={'class': INPUT_CLASSES}),
            'position': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'monthly_salary': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'wish_to_deposit': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'refund_on_exit': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'deposits': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'loan': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'share_holding': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'active_user': forms.CheckboxInput(attrs={'class': INPUT_CLASSES}),
        }


class MemberSearchForm(forms.Form):
    search_query = forms.CharField(label='Search', required=False,
                                   widget=forms.TextInput(
                                       attrs={'placeholder': 'Enter name or Membership No.',
                                              'class': SEARCH_INPUT_CLASSES}))
    branch = forms.ModelChoiceField(queryset=Branch.objects.all(), empty_label='All Branches', required=False,
                                    widget=forms.Select(attrs={'class': SEARCH_INPUT_CLASSES}))

member/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import MemberForm, EditMemberForm, MemberSearchForm
from .models import Member


# Create your views here.

def home(request):
    return render(request, 'member/home.html')


def create_member(request):
    if request.method == 'POST':
        form = MemberForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('member:member-home')
    else:
        form = MemberForm()

    return render(request, 'member/create-member.html', {'form': form})


def member_edit_search_view(request):
    form = MemberSearchForm(request.GET)
    members = Member.objects.all()

    if form.is_valid():
        search_query = form.cleaned_data.get('search_query')
        branch = form.cleaned_data.get('branch')

        if search_query:
            members = members.filter(name__icontains=search_query) | members.filter(id__icontains=search_query)

        if branch:
            members = members.filter(branch=branch)

    context = {
        'form': form,
        'members': members
    }

    return render(request, 'member/edit-member.html', context)


def edit_selected_member(request, pk):
    member = get_object_or_404(Member, pk=pk)

    if request.method == 'POST':
        form = EditMemberForm(request.POST, instance=member)

        if form.is_valid():
            member.active_user = True
            form.save()

            return redirect('member:member-edit')
    else:
        form = EditMemberForm(instance=member)

    return render(request, 'member/edit-member-pk.html', {
        'form': form,
        'title': 'Edit member',
    })


def remove_member(request):
    form = MemberSearchForm(request.GET)
    members = Member.objects.all()

    if form.is_valid():
        search_query = form.cleaned_data.get('search_query')
        branch = form.cleaned_data.get('branch')

        if search_query:
            members = members.filter(name__icontains=search_query) | members.filter(id__icontains=search_query)

        if branch:
            members = members.filter(branch=branch)

    context = {
        'form': form,
        'members': members
    }

    return render(request, 'member/remove-member.html', context)


def remove_selected_member(request, pk):
    member = get_object_or_404(Member, pk=pk)

    # delete on click
    member.active_user = False
    # uncomment to delete member data
    # member.delete()
    member.save()
    return redirect('member:member-remove')


def view_member(request):
    form = MemberSearchForm(request.GET)
    members = Member.objects.all()

    if form.is_valid():
        search_query = form.cleaned_data.get('search_query')
        branch = form.cleaned_data.get('branch')

        if search_query:
            members = members.filter(name__icontains=search_query) | members.filter(id__icontains=search_query)

        if branch:
            members = members.filter(branch=branch)

    context = {
        'form': form,
        'members': members
    }

    return render(request, 'member/list_member.html', context)


def view_selected_member(request, pk):
    member = get_object_or_404(Member, pk=pk)

    context = {
        'member': member,
    }

    return render(request, 'member/detail-member.html', context)


def terminated_members(request):
    form = MemberSearchForm(request.GET)
    members = Member.objects.all()
    members = members.filter(active_user=False)

    if form.is_valid():
        search_query = form.cleaned_data.get('search_query')
        branch = form.cleaned_data.get('branch')

        if search_query:
            members = members.filter(name__icontains=search_query) | members.filter(id__icontains=search_query)

        if branch:
            members = members.filter(branch=branch)

    context = {
        'form': form,
        'members': members
    }

    return render(request, 'member/terminated-members.html', context)

member/templates/member/create-member.html
{% extends 'core/base.html' %}

{% block title %}Create Member{% endblock %}
{% block heading %}Create Member{% endblock %}

{% block content %}
    <div class="max-w-full mx-auto bg-gray-200 p-6 rounded-lg shadow-lg">
        {#        <h1 class="text-3xl font-bold mb-6">Dashboard</h1>#}

        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}

            <!-- First three entries -->


            <!-- Last six entries -->
            <div class="grid grid-cols-2 gap-4">
                <div class="mb-4">
                    <label for="{{ form.id.id_for_label }}" class="font-bold">Membership No.</label>
                    {{ form.id }}
                </div>
                <div class="mb-4">
                    <label for="{{ form.name.id_for_label }}" class="font-bold">Name</label>
                    {{ form.name }}
                </div>
                <div class="mb-4">
                    <label for="{{ form.branch.id_for_label }}" class="font-bold">Branch</label>
                    {{ form.branch }}
                </div>
                <div class="mb-4">
                    <label for="{{ form.position.id_for_label }}" class="font-bold">Position</label>
                    {{ form.position }}
                </div>
                <div class="mb-4">
                    <label for="{{ form.monthly_salary.id_for_label }}" class="font-bold">Monthly Salary</label>
                    {{ form.monthly_salary }}
                </div>
                <div class="mb-4">
                    <label for="{{ form.wish_to_deposit.id_for_label }}" class="font-bold">Monthly Deposit</label>
                    {{ form.wish_to_deposit }}
                </div>
                <div class="mb-4">
                    <label for="{{ form.refund_on_exit.id_for_label }}" class="font-bold">Accumulated NRD</label>
                    {{ form.refund_on_exit }}
                </div>
                <div class="mb-4">
                    <label for="{{ form.deposits.id_for_label }}" class="font-bold">Deposit Balance</label>
                    {{ form.deposits }}
                </div>
                <div class="mb-4">
                    <label for="{{ form.loan.id_for_label }}" class="font-bold">Issued Loan amount</label>
                    {{ form.loan }}
                </div>
                <div class="mb-4">
                    <label for="{{ form.share_holding.id_for_label }}" class="font-bold">Share Holding Amount</label>
                    {{ form.share_holding }}
                </div>
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <div class="flex justify-end mt-6">
                <button class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded">Save</button>
            </div>
        </form>
    </div>
{% endblock %}

member/templates/member/detail-member.html
{% extends 'core/base.html' %}
{% block title %}Member Details{% endblock %}
{% block heading %}Member Details - {{ member.name }}{% endblock %}
{% block content %}
    <div class="container mx-auto px-4 py-8 max-w-full mx-auto bg-gray-200 rounded-lg shadow-lg">
        <div class="grid grid-cols-2 gap-4">
            <div class="mb-4">
                <label class="font-bold">Membership No.</label>
                <p>{{ member.id }}</p>
            </div>
            <div class="mb-4">
                <label class="font-bold">Name</label>
                <p>{{ member.name }}</p>
            </div>
            <div class="mb-4">
                <label class="font-bold">Branch</label>
                <p>{{ member.branch }}</p>
            </div>
            <div class="mb-4">
                <label class="font-bold">Position</label>
                <p>{{ member.position }}</p>
            </div>
            <div class="mb-4">
                <label class="font-bold">Monthly Salary</label>
                <p>{{ member.monthly_salary }}</p>
            </div>
            <div class="mb-4">
                <label class="font-bold">Monthly Deposit</label>
                <p>{{ member.wish_to_deposit }}</p>
            </div>
            <div class="mb-4">
                <label class="font-bold">Accumulated NRD</label>
                <p>{{ member.refund_on_exit }}</p>
            </div>
            <div class="mb-4">
                <label class="font-bold">Deposit Balance</label>
                <p>{{ member.deposits }}</p>
            </div>
            <div class="mb-4">
                <label class="font-bold">Issued Loan Amount</label>
                <p>{{ member.loan }}</p>
            </div>
            <div class="mb-4">
                <label class="font-bold">Share Holding Amount</label>
                <p>{{ member.share_holding }}</p>
            </div>
            <div class="mb-4">
                <label class="font-bold">Membership Status</label>
                <p>{{ member.active_user }}</p>
            </div>
        </div>
    </div>
{% endblock %}

member/templates/member/edit-member.html
<!-- member_search.html -->
{% extends 'core/base.html' %}
{% block title %}Edit Member{% endblock %}
{% block heading %}Member Search{% endblock %}
{% block content %}
    <div class="container mx-auto px-4 py-8 max-w-full mx-auto bg-gray-200 rounded-lg shadow-lg">
        <div class="flex justify-center items-center">
            <div>
                <form method="GET" action="">
                    {#                    {{ form.as_p }}#}
                    <div class="mb-4">
                        <label for="{{ form.search_query.id_for_label }}" class="font-bold">Search</label>
                        {{ form.search_query }}
                    </div>
                    <div class="mb-4">
                        <label for="{{ form.branch.id_for_label }}" class="font-bold">Branch</label>
                        {{ form.branch }}
                    </div>
                    <div class="flex justify-center">
                        <button type="submit"
                                class="inline-block bg-blue-500 hover:bg-blue-700 text-white py-2 px-6 rounded">
                            Search
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <div class="mt-8">
            <h2 class="text-2xl font-bold mb-4">Filtered Members:</h2>
            {% if members %}
                <ul>
                    <table class="w-full border-collapse">
                        <colgroup>
                            <col style="width: 45%;">
                            <col style="width: 45%;">
                            <col style="width: 10%;">
                        </colgroup>
                        <thead>
                        <tr>
                            <th class="border-4 border-gray-500 px-4 py-2">Membership No.</th>
                            <th class="border-4 border-gray-500 px-4 py-2">Name</th>
                            <th class="border-4 border-gray-500 px-4 py-2">Edit</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for member in members %}
                            {% if member.active_user %}
                                <tr>
                                    <td class="border border-gray-500 px-4 py-2">{{ member.id }}</td>
                                    <td class="border border-gray-500 px-4 py-2">{{ member.name }}</td>
                                    <td class="border border-gray-500 px-4 py-2">
                                        <a href="{% url 'member:member-edit-pk' member.id %}"
                                           class="inline-block bg-blue-500 hover:bg-blue-700 text-white py-2 px-6 rounded">Edit</a>
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </ul>
            {% else %}
                <p>No members found.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

member/templates/member/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Manage Members{% endblock %}
{% block heading %}Manage Members{% endblock %}
{% block content %}
    <div class="flex justify-center items-center">
        <div class="space-y-4 container mx-auto px-4 py-8 max-w-xl mx-auto bg-gray-200 rounded-lg shadow-lg">
            <div class="flex flex-col space-y-4">
                <div class="flex flex-row space-x-4">
                    <a href="{% url "member:member-create" %}" class="btn btn-blue">
                        Add a New Member
                    </a>
                    <a href="{% url "member:member-edit" %}" class="btn btn-yellow">
                        Edit Existing Member
                    </a>
                    <a href="{% url "member:member-remove" %}" class="btn btn-red">
                        Terminate Membership
                    </a>
                </div>
                <a href="{% url "member:member-view" %}" class="btn btn-gray">
                    Search for a Member
                </a>
                <a href="{% url "accounts:cashbook-search" %}" class="btn btn-green">
                    Search Member's Ledger
                </a>
                <a href="{% url "member:member-terminated" %}" class="btn btn-purple">
                    Terminated Members
                </a>
            </div>
        </div>
    </div>
    <style>
        .btn {
            display: inline-block;
            padding: 0.75rem 1.5rem;
            font-weight: bold;
            text-align: center;
            text-decoration: none;
            border-radius: 0.375rem;
            transition: all 0.3s ease;
        }

        .btn-blue {
            background-color: #3B82F6;
            color: #FFFFFF;
        }

        .btn-yellow {
            background-color: #F59E0B;
            color: #FFFFFF;
        }

        .btn-red {
            background-color: #EF4444;
            color: #FFFFFF;
        }

        .btn-green {
            background-color: #10B981;
            color: #FFFFFF;
        }

        .btn-purple {
            background-color: #8B5CF6;
            color: #FFFFFF;
        }

        .btn-gray {
            background-color: #9CA3AF;
            color: #FFFFFF;
        }

        .btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.15);
        }
    </style>
{% endblock %}

member/templates/member/list_member.html
<!-- member_search.html -->
{% extends 'core/base.html' %}
{% block title %}View Member Details{% endblock %}
{% block heading %}Member Search{% endblock %}
{% block content %}
    <div class="container mx-auto px-4 py-8 max-w-full mx-auto bg-gray-200 rounded-lg shadow-lg">
        <div class="flex justify-center items-center">
            <div>
                <form method="GET" action="">
                    {#                    {{ form.as_p }}#}
                    <div class="mb-4">
                        <label for="{{ form.search_query.id_for_label }}" class="font-bold">Search</label>
                        {{ form.search_query }}
                    </div>
                    <div class="mb-4">
                        <label for="{{ form.branch.id_for_label }}" class="font-bold">Branch</label>
                        {{ form.branch }}
                    </div>
                    <div class="flex justify-center">
                        <button type="submit"
                                class="inline-block bg-teal-500 hover:bg-teal-700 text-white py-2 px-6 rounded">
                            Search
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <div class="mt-8">
            <h2 class="text-2xl font-bold mb-4">Filtered Members:</h2>
            {% if members %}
                <ul>
                    <table class="w-full border-collapse">
                        <colgroup>
                            <col style="width: 45%;">
                            <col style="width: 45%;">
                            <col style="width: 10%;">
                        </colgroup>
                        <thead>
                        <tr>
                            <th class="border-4 border-gray-500 px-4 py-2">Membership No.</th>
                            <th class="border-4 border-gray-500 px-4 py-2">Name</th>
                            <th class="border-4 border-gray-500 px-4 py-2">View</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for member in members %}
                            {% if member.active_user %}
                                <tr>
                                    <td class="border border-gray-500 px-4 py-2">{{ member.id }}</td>
                                    <td class="border border-gray-500 px-4 py-2">{{ member.name }}</td>
                                    <td class="border border-gray-500 px-4 py-2">
                                        <a href="{% url 'member:member-view-pk' member.id %}"
                                           class="inline-block bg-teal-500 hover:bg-teal-700 text-white py-2 px-6 rounded">View</a>
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </ul>
            {% else %}
                <p>No members found.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

member/templates/member/remove-member.html
<!-- member_search.html -->
{% extends 'core/base.html' %}
{% block title %}Remove Member{% endblock %}
{% block heading %}Remove Member{% endblock %}
{% block content %}
    <div class="container mx-auto px-4 py-8 max-w-full mx-auto bg-gray-200 rounded-lg shadow-lg">
        <div class="flex justify-center items-center">
            <div>
                <form method="GET" action="">
                    {#                    {{ form.as_p }}#}
                    <div class="mb-4">
                        <label for="{{ form.search_query.id_for_label }}" class="font-bold">Search</label>
                        {{ form.search_query }}
                    </div>
                    <div class="mb-4">
                        <label for="{{ form.branch.id_for_label }}" class="font-bold">Branch</label>
                        {{ form.branch }}
                    </div>
                    <div class="flex justify-center">
                        <button type="submit"
                                class="inline-block bg-red-500 hover:bg-red-700 text-white py-2 px-6 rounded">
                            Search
                        </button>
                    </div>

                </form>
            </div>
        </div>

        <div class="mt-8">
            <h2 class="text-2xl font-bold mb-4">Filtered Members:</h2>
            {% if members %}
                <ul>
                    <table class="w-full border-collapse">
                        <colgroup>
                            <col style="width: 45%;">
                            <col style="width: 45%;">
                            <col style="width: 10%;">
                        </colgroup>
                        <thead>
                        <tr>
                            <th class="border-4 border-gray-500 px-4 py-2">Membership No.</th>
                            <th class="border-4 border-gray-500 px-4 py-2">Name</th>
                            <th class="border-4 border-gray-500 px-4 py-2">Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for member in members %}
                            {% if member.active_user %}
                                <tr>
                                    <td class="border border-gray-500 px-4 py-2">{{ member.id }}</td>
                                    <td class="border border-gray-500 px-4 py-2">{{ member.name }}</td>
                                    <td class="border border-gray-500 px-4 py-2">
                                        <a href="{% url 'member:member-remove-pk' member.id %}"
                                           class="inline-block bg-red-500 hover:bg-red-700 text-white py-2 px-6 rounded">Delete</a>
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </ul>
            {% else %}
                <p>No members found.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

member/templates/member/terminated-members.html
<!-- member_search.html -->
{% extends 'core/base.html' %}
{% block title %}View Member Details{% endblock %}
{% block heading %}Member Search{% endblock %}
{% block content %}
    <div class="container mx-auto px-4 py-8 max-w-full mx-auto bg-gray-200 rounded-lg shadow-lg">
        <div class="flex justify-center items-center">
            <div>
                <form method="GET" action="">
                    {#                    {{ form.as_p }}#}
                    <div class="mb-4">
                        <label for="{{ form.search_query.id_for_label }}" class="font-bold">Search</label>
                        {{ form.search_query }}
                    </div>
                    <div class="mb-4">
                        <label for="{{ form.branch.id_for_label }}" class="font-bold">Branch</label>
                        {{ form.branch }}
                    </div>
                    <div class="flex justify-center">
                        <button type="submit"
                                class="inline-block bg-yellow-500 hover:bg-yellow-700 text-white py-2 px-6 rounded">
                            Search
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <div class="mt-8">
            <h2 class="text-2xl font-bold mb-4">Filtered Members:</h2>
            {% if members %}
                <ul>
                    <table class="w-full border-collapse">
                        <colgroup>
                            <col style="width: 45%;">
                            <col style="width: 45%;">
                            <col style="width: 10%;">
                        </colgroup>
                        <thead>
                        <tr>
                            <th class="border-4 border-gray-500 px-4 py-2">Membership No.</th>
                            <th class="border-4 border-gray-500 px-4 py-2">Name</th>
                            <th class="border-4 border-gray-500 px-4 py-2">View</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for member in members %}
                            <tr>
                                <td class="border border-gray-500 px-4 py-2">{{ member.id }}</td>
                                <td class="border border-gray-500 px-4 py-2">{{ member.name }}</td>
                                <td class="border border-gray-500 px-4 py-2">
                                    <a href="{% url 'member:member-view-pk' member.id %}"
                                       class="inline-block bg-yellow-500 hover:bg-yellow-700 text-white py-2 px-6 rounded">View</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </ul>
            {% else %}
                <p>No members found.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}