FundConnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('branch/', include('branch.urls'), name='branch'),
    path('member/', include('member.urls'), name='member'),
    path('accounts/', include('accounts.urls'), name='accounts'),
]

accounts/urls.py
# @Project:     FundConnect
# @Filename:    urls.py
# @Author:      Daksh Gaur
# @Email:       hi@daksh.fyi
# @Time:        24-06-2023 03:40 pm
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='cashbook-home'),
    path('create/', views.create_cashbook_entry, name='cashbook-create'),
    path('search/', views.search_cashbook, name='cashbook-search'),
    path('<int:pk>/<str:financial_year>/cashbook/', views.view_cashbook, name='cashbook-view'),
    path('transactions/', views.search_transactions, name='transactions-search'),
    path('<str:year>/<str:month>/<str:date>/transactions/', views.transaction_by_date, name='transactions-view'),
    path('all/', views.view_all_cashbook, name='cashbook-all'),
    path('branch/', views.create_branch_entry, name='branch-cashbook-create'),
    path('branch/<int:date>/<int:month>/<int:year>/', views.list_branch_for_entry, name='cashbook-branches-list'),
    path('branch/<int:pk>/<int:date>/<int:month>/<int:year>/', views.create_entry_for_selected_branch,
         name='cashbook-entry-selected-branch'),
    path('apply-for-loan/', views.loan_application, name='loan-apply'),
]

branch/urls.py
# @Project:     FundConnect
# @Filename:    urls.py
# @Author:      Daksh
# @Time:        08-06-2023 01:09 pm
from django.urls import path
from . import views

app_name = 'branch'

urlpatterns = [
    path('', views.home, name='branch-home'),
    path('<int:pk>/', views.detail_branch, name='branch-detail-pk'),
    path('create/', views.create_branch, name='branch-create'),
    path('list/', views.list_branch, name='branch-list'),
    path('remittance/', views.remittance_form_view, name='branch-remittance'),
    path('edit/', views.edit_branch, name='branch-edit'),
    path('remove/', views.remove_branch, name='branch-remove'),
    path('<int:pk>/edit/', views.edit_selected_branch, name='branch-edit-pk'),

]

core/urls.py
# @Project:     FundConnect
# @Filename:    urls.py
# @Author:      Daksh
# @Time:        08-06-2023 12:38 pm

from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('dev-guide/', views.dev_guide, name='dev-guide'),
]

accounts/models.py
from django.db import models
from member.models import Member
from django.core.validators import RegexValidator
from dashboard.models import Controller
from .calculations import helper_functions


class Cashbook(models.Model):
    financial_year_validator = RegexValidator(
        regex=r'^\d{4}-\d{2}$',
        message="Financial year must be in the format 'YYYY-YY'"
    )

    financial_year = models.CharField(
        max_length=7,
        validators=[financial_year_validator]
    )
    member = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='cashbooks')

    def __str__(self):
        return f"{self.financial_year} - {self.member.id} {self.member.name}"


class CashBookEntry(models.Model):
    FUND_TYPES = [
        ('OPENING BALANCE', 'Opening_Balance'),
        ('CLOSING BALANCE', 'Closing_Balance'),
        ('INTEREST', 'Interest'),
        ('DIVIDEND', 'Dividend'),
        ('SALARY', 'Salary'),
        ('DEPOSIT', 'Deposit'),
        ('ADJUSTMENT', 'Adjustment'),
        ('CHEQUE', 'Cheque'),
        ('SERVICE_FEE', 'Service Fee'),
        ('OTHER', 'Other'),
        ('LOAN', 'Loan'),
        ('SHARES', 'Shares'),
    ]

    date = models.IntegerField()
    month = models.IntegerField()
    year = models.IntegerField()
    fund_type = models.CharField(max_length=20, choices=FUND_TYPES)
    refund_on_exit_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    deposits_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    loan_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    shares_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    cashbook = models.ForeignKey(Cashbook, on_delete=models.CASCADE, related_name='entries')
    remittance_posted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.date}-{self.month}-{self.year}: {self.fund_type}, {self.member.id} {self.member.name}"

    def save(self, *args, **kwargs):
        # Automatically determine the cashbook based on the financial year
        financial_year = helper_functions.get_financial_year(self.month, self.year)

        cashbook, created = Cashbook.objects.get_or_create(
            financial_year=financial_year,
            member=self.member
        )

        if self.fund_type not in ['OPENING BALANCE', 'CLOSING BALANCE', 'LOAN', 'SHARES']:
            self.member.refund_on_exit += self.refund_on_exit_amount
            self.member.deposits += self.deposits_amount
            self.member.loan += self.loan_amount
            self.member.share_holding += self.shares_amount
            self.member.save()

        self.cashbook = cashbook
        super().save(*args, **kwargs)


class Loan(models.Model):
    date = models.IntegerField()
    month = models.IntegerField()
    year = models.IntegerField()
    ask_loan_amount = models.DecimalField(max_digits=10, decimal_places=2)
    allotted_loan_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    allotted_to_member = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='loans')
    number_of_installments = models.IntegerField(default=120)

branch/models.py
from django.db import models


# Create your models here.
class Branch(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=300)
    location = models.CharField(max_length=300)
    manager = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f"{self.name}, {self.location}"

branch/forms.py
# @Project:     FundConnect
# @Filename:    forms.py
# @Author:      Daksh
# @Time:        08-06-2023 01:27 pm

from django import forms
from .models import Branch

# styling
INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'


class BranchForm(forms.ModelForm):
    class Meta:
        model = Branch
        fields = ('name', 'location', 'manager')
        labels = {'name': 'Name', 'location': 'Location', 'manager': 'Manager'}
        widgets = {
            'name': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'location': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'manager': forms.TextInput(attrs={'class': INPUT_CLASSES}),
        }


class EditBranchForm(forms.ModelForm):
    class Meta:
        model = Branch
        fields = ('name', 'location', 'manager')
        labels = {'name': 'Name', 'location': 'Location', 'manager': 'Manager'}
        widgets = {
            'name': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'location': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'manager': forms.TextInput(attrs={'class': INPUT_CLASSES}),
        }

branch/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import BranchForm, EditBranchForm
from .models import Branch
from member.models import Member
from dashboard.models import Controller


# Create your views here.

def home(request):
    return render(request, 'branch/home.html')


def create_branch(request):
    if request.method == 'POST':
        form = BranchForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('branch:branch-edit')
    else:
        form = BranchForm()

    return render(request, 'branch/create-branch.html', {'form': form})


def list_branch(request):
    branches = Branch.objects.all()
    context = {
        'branches': branches,
    }
    return render(request, 'branch/list-branches.html', context)


# not in use
# but kept for reference
def detail_branch(request, pk):
    branch = get_object_or_404(Branch, pk=pk)
    context = {
        'branch': branch,
    }
    return render(request, 'branch/detail-branch.html', context)


def edit_selected_branch(request, pk):
    branch = get_object_or_404(Branch, pk=pk)

    if request.method == 'POST':
        form = EditBranchForm(request.POST, instance=branch)

        if form.is_valid():
            form.save()

            return redirect('branch:branch-edit')
    else:
        form = EditBranchForm(instance=branch)

    return render(request, 'branch/edit-branch-pk.html', {
        'form': form,
        'title': 'Edit branch',
    })


def edit_branch(request):
    branches = Branch.objects.all()
    context = {
        'branches': branches,
    }
    return render(request, 'branch/edit-branch.html', context)


def remove_branch(request):
    return render(request, 'branch/remove-branch.html')


def remittance_form_view(request):
    if request.method == 'POST':
        date = request.POST.get('date')
        month = request.POST.get('month')
        year = request.POST.get('year')

        branches = Branch.objects.all()
        controller = Controller.objects.all().first()
        members = Member.objects.all()
        members = members.filter(active_user=True)

        # Calculations

        loan_emi = {}
        loan_interest = {}

        for member in members:
            # add loan emi and key is id
            loan_emi[member.id] = round(member.loan / 12, 2)  # will change later
            loan_interest[member.id] = round(member.loan * (
                    controller.loan_interest / 100),
                                             2)  # will change later, according to controller.loan_interest_period

        context = {
            'date': date,
            'month': month,
            'year': year,
            'branches': branches,
            'members': members,
            'controller': controller,
            'loan_emi': loan_emi,
            'loan_interest': loan_interest,
        }

        return render(request, 'branch/remittance-template.html', context)

    return render(request, 'branch/remittance-form.html')

branch/templates/branch/create-branch.html
{% extends 'core/base.html' %}

{% block title %}Create Branch{% endblock %}
{% block heading %}Create Branch{% endblock %}

{% block content %}
    <div class="max-w-md mx-auto bg-white p-6 rounded-lg shadow-lg">
        {#        <h1 class="text-3xl font-bold mb-4">Create Branch</h1>#}

        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}

            <div class="space-y-4">
                {{ form.as_p }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-4 p-4 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="mt-6 py-3 px-6 bg-teal-500 hover:bg-teal-700 text-white font-semibold rounded-lg shadow-lg">
                Submit
            </button>
        </form>
    </div>
{% endblock %}

branch/templates/branch/detail-branch.html
{% extends 'core/base.html' %}

{#Not in use, but kept for reference#}

{% block title %}View Branch{% endblock %}
{% block heading %}View Branch{% endblock %}

{% block content %}
    <div class="container mx-auto px-4 py-8">
        <h1 class="text-3xl font-bold mb-6">View Branch</h1>

        <ul>
            <table class="w-full">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Location</th>
                    <th>Manager<</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ branch.name }}</td>
                    <td>{{ branch.location }}</td>
                    <td>{{ branch.manager }}</td>
                </tr>

                </tbody>
            </table>
        </ul>
    </div>
{% endblock %}

branch/templates/branch/edit-branch-pk.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">{{ title }}</h1>

    <div class="max-w-md mx-auto bg-gray-200 p-6 rounded-lg shadow-lg">
        {#  enctype is for file upload  #}
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}

            {#            <div class="space-y-6">#}
            {#                {{ form.as_p }}#}
            {#            </div>#}

            <div class="mb-4">
                <label for="{{ form.name.id_for_label }}" class="font-bold">Branch Name</label>
                {{ form.name }}
            </div>
            <div class="mb-4">
                <label for="{{ form.location.id_for_label }}" class="font-bold">Location</label>
                {{ form.location }}
            </div>
            <div class="mb-4">
                <label for="{{ form.manager.id_for_label }}" class="font-bold">Branch Manager</label>
                {{ form.manager }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}


            <button class="bg-blue-500 hover:bg-blue-700 text-white py-1 px-4 rounded space-y-6">Submit</button>

        </form>
    </div>
{% endblock %}

branch/templates/branch/edit-branch.html
{% extends 'core/base.html' %}

{% block title %}Edit Branch{% endblock %}
{% block heading %}Edit Branch{% endblock %}

{% block content %}
    <div class="container mx-auto px-4 py-8 max-w-full mx-auto bg-gray-200 rounded-lg shadow-lg">
        {#        <h1 class="text-3xl font-bold mb-6">Edit Branch</h1>#}

        <ul>
            <table class="w-full border-collapse">
                <colgroup>
                    <col style="width: 45%;">
                    <col style="width: 45%;">
                    <col style="width: 10%;">
                </colgroup>
                <thead>
                <tr>
                    <th class="border-4 border-gray-500 px-4 py-2">Name</th>
                    <th class="border-4 border-gray-500 px-4 py-2">Location</th>
                    <th class="border-4 border-gray-500 px-4 py-2">Edit</th>
                </tr>
                </thead>
                <tbody>
                {% for branch in branches %}
                    <tr>
                        <td class="border border-gray-500 px-4 py-2">{{ branch.name }}</td>
                        <td class="border border-gray-500 px-4 py-2">{{ branch.location }}</td>
                        <td class="border border-gray-500 px-4 py-2">
                            <a href="{% url 'branch:branch-edit-pk' branch.id %}"
                               class="inline-block bg-blue-500 hover:bg-blue-700 text-white py-2 px-6 rounded">Edit</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </ul>
    </div>
{% endblock %}

branch/templates/branch/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Manage Branch{% endblock %}
{% block heading %}Manage Branch{% endblock %}
{% block content %}
    <div class="flex justify-center items-center">
        <div class="space-y-4 container mx-auto px-4 py-8 max-w-xl mx-auto bg-gray-200 rounded-lg shadow-lg">
            <div class="flex flex-col space-y-4">
                <div class="flex flex-row space-x-4">
                    <a href="{% url "branch:branch-create" %}" class="btn btn-blue">
                        Add a New Branch
                    </a>
                    <a href="{% url 'branch:branch-edit' %}" class="btn btn-yellow">
                        Edit Existing Branch
                    </a>
                    <a href="{% url "branch:branch-remove" %}" class="btn btn-red">
                        Remove a Branch
                    </a>
                </div>
                <a href="{% url "branch:branch-list" %}" class="btn btn-gray">
                    List All Branches
                </a>
                <a href="{% url "branch:branch-remittance" %}" class="btn btn-green">
                    Create Remittance
                </a>
                <a href="{% url "accounts:branch-cashbook-create" %}" class="btn btn-purple">
                    Post Remittance
                </a>
            </div>
        </div>
    </div>
    <style>
        .btn {
            display: inline-block;
            padding: 0.75rem 1.5rem;
            font-weight: bold;
            text-align: center;
            text-decoration: none;
            border-radius: 0.375rem;
            transition: all 0.3s ease;
        }

        .btn-blue {
            background-color: #3B82F6;
            color: #FFFFFF;
        }

        .btn-yellow {
            background-color: #F59E0B;
            color: #FFFFFF;
        }

        .btn-red {
            background-color: #EF4444;
            color: #FFFFFF;
        }

        .btn-green {
            background-color: #10B981;
            color: #FFFFFF;
        }

        .btn-purple {
            background-color: #8B5CF6;
            color: #FFFFFF;
        }

        .btn-gray {
            background-color: #9CA3AF;
            color: #FFFFFF;
        }

        .btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.15);
        }
    </style>
{% endblock %}

branch/templates/branch/list-branches.html
{% extends 'core/base.html' %}
{% block title %} List of Branches {% endblock %}
{% block heading %} List of Branches {% endblock %}
{% block content %}
    <div class="container mx-auto px-4 py-8 max-w-full mx-auto bg-gray-200 rounded-lg shadow-lg">
        {#        <h1 class="text-3xl font-bold mb-6">List of Branches</h1>#}

        <ul class="space-y-4">
            <li class="flex items-center space-x-4 border border-gray-900 border-4 px-4 py-2">
                <div class="flex-1">
                    <h2 class="text-xl font-bold text-blue-800">Branch Name</h2>
                    <p class="text-gray-500 text-blue-500">Branch Location </p>
                </div>
                <div class="text-sm text-gray-500 text-blue-800">
                    No. of Members
                </div>
            </li>
            {% for branch in branches %}
                <li class="flex items-center space-x-4 border border-gray-400 px-4 py-2">
                    <div class="flex-1">
                        <h2 class="text-xl font-bold">{{ branch.name }}</h2>
                        <p class="text-gray-500">{{ branch.location }}</p>
                    </div>
                    <div class="text-sm text-gray-500">
                        {{ branch.member_count }} Members
                    </div>
                </li>
            {% empty %}
                <li>No branches available</li>
                <a href="{% url "branch:branch-create" %}"
                   class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded">
                    Add a New Branch
                </a>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

branch/templates/branch/remittance-form.html
{% extends 'core/base.html' %}

{% block title %}Remittance Form{% endblock %}
{% block heading %}Remittance Form{% endblock %}

{% block content %}
    <div class="max-w-full mx-auto bg-gray-200 p-6 rounded-lg shadow-lg">
        <form method="POST" action="." target="_blank">
            {% csrf_token %}
            <div class="mb-4">
                <label for="id_date" class="font-bold">Date (MM)</label>
                <input type="number" name="date" id="id_date" required>
            </div>
            <div class="mb-4">
                <label for="id_month" class="font-bold">Month (MM)</label>
                <input type="number" name="month" id="id_month" required>
            </div>
            <div class="mb-4">
                <label for="id_year" class="font-bold">Year (YYYY)</label>
                <input type="number" name="year" id="id_year" required>
            </div>
            <button class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded">Generate</button>
        </form>
    </div>
{% endblock %}

branch/templates/branch/remittance-template.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/output.css" %}">
</head>
{% for branch in branches %}
    {% if branch.members.all %}
        <div>
            <div class="flex flex-col items-center justify-center">
                <h1 class="text-4xl font-bold mb-4">Branch Name: {{ branch.name }}</h1>
                <p class="text-xl mb-2">Branch Location: {{ branch.location }}</p>
                <p class="text-xl mb-2">Remittance for: {{ month }}, {{ year }}</p>
            </div>

            <div class="mt-4"></div> <!-- Add line space here -->
            <div class="max-w-full mx-auto">
                <table class="border-collapse border">
                    <thead>
                    <tr>
                        <th class="border p-2">Member ID</th>
                        <th class="border p-2">Member Name</th>
                        <th class="border p-2">NRD</th>
                        <th class="border p-2">Wish to Deposit Amount</th>
                        <th class="border p-2">Loan EMI</th>
                        <th class="border p-2">Loan Interest</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for member in branch.members.all %}
                        {% if member.active_user %}
                            <tr>
                                <td class="border p-2">{{ member.id }}</td>
                                <td class="border p-2">{{ member.name }}</td>
                                <td class="border p-2">{{ controller.refund_on_exit_monthly_deposit }}</td>
                                <td class="border p-2">{{ member.wish_to_deposit }}</td>
                                <td class="border p-2">{{ loan_emi|get_item:member.id }}</td>
                                <td class="border p-2">{{ loan_interest|get_item:member.id }}</td>
                            </tr> {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Add a page break after each branch's data -->
        <div style="page-break-after: always;"></div>
    {% endif %}
{% endfor %}

</html>

branch/templates/branch/remove-branch.html
{% extends 'core/base.html' %}

{% block title %}Edit Branch{% endblock %}
{% block heading %}Edit Branch{% endblock %}

{% block content %}
    <div class="container mx-auto px-4 py-8 max-w-full mx-auto bg-gray-200 rounded-lg shadow-lg">
        <p class="text-center text-2xl font-bold text-red-900">Warning! Deleting a branch will also delete all the data
            associated to the members of that branch. Are you sure you want to delete any branch?</p>
        <p class="text-center text-md font-bold text-black"> If yes, then
            login to admin portal to delete the branch. To access admin portal visit home-link/admin and enter the
            credentials.</p>
    </div>
{% endblock %}