FundConnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('branch/', include('branch.urls'), name='branch'),
    path('member/', include('member.urls'), name='member'),
    path('accounts/', include('accounts.urls'), name='accounts'),
]

accounts/urls.py
# @Project:     FundConnect
# @Filename:    urls.py
# @Author:      Daksh Gaur
# @Email:       hi@daksh.fyi
# @Time:        24-06-2023 03:40 pm
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='cashbook-home'),
    path('create/', views.create_cashbook_entry, name='cashbook-create'),
    path('search/', views.search_cashbook, name='cashbook-search'),
    path('<int:pk>/<str:financial_year>/cashbook/', views.view_cashbook, name='cashbook-view'),
    path('transactions/', views.search_transactions, name='transactions-search'),
    path('<str:year>/<str:month>/<str:date>/transactions/', views.transaction_by_date, name='transactions-view'),
    path('all/', views.view_all_cashbook, name='cashbook-all'),
    path('branch/', views.create_branch_entry, name='branch-cashbook-create'),
    path('branch/<int:date>/<int:month>/<int:year>/', views.list_branch_for_entry, name='cashbook-branches-list'),
    path('branch/<int:pk>/<int:date>/<int:month>/<int:year>/', views.create_entry_for_selected_branch,
         name='cashbook-entry-selected-branch'),
    path('apply-for-loan/', views.loan_application, name='loan-apply'),
]

branch/urls.py
# @Project:     FundConnect
# @Filename:    urls.py
# @Author:      Daksh
# @Time:        08-06-2023 01:09 pm
from django.urls import path
from . import views

app_name = 'branch'

urlpatterns = [
    path('', views.home, name='branch-home'),
    path('<int:pk>/', views.detail_branch, name='branch-detail-pk'),
    path('create/', views.create_branch, name='branch-create'),
    path('list/', views.list_branch, name='branch-list'),
    path('remittance/', views.remittance_form_view, name='branch-remittance'),
    path('edit/', views.edit_branch, name='branch-edit'),
    path('remove/', views.remove_branch, name='branch-remove'),
    path('<int:pk>/edit/', views.edit_selected_branch, name='branch-edit-pk'),

]

core/urls.py
# @Project:     FundConnect
# @Filename:    urls.py
# @Author:      Daksh
# @Time:        08-06-2023 12:38 pm

from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('dev-guide/', views.dev_guide, name='dev-guide'),
]

dashboard/urls.py
# @Project:     FundConnect
# @Filename:    urls.py
# @Author:      Daksh
# @Time:        08-06-2023 01:08 pm
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('edit/', views.edit_dashboard, name='dashboard-edit'),
    path('', views.view_dashboard, name='dashboard-home'),
]

member/urls.py
# @Project:     FundConnect
# @Filename:    urls.py
# @Author:      Daksh
# @Time:        08-06-2023 01:09 pm
from django.urls import path
from . import views

app_name = 'member'

urlpatterns = [
    path('', views.home, name='member-home'),
    path('create/', views.create_member, name='member-create'),
    path('edit/', views.member_edit_search_view, name='member-edit'),
    path('<int:pk>/edit/', views.edit_selected_member, name='member-edit-pk'),
    path('remove/', views.remove_member, name='member-remove'),
    path('<int:pk>/remove/', views.remove_selected_member, name='member-remove-pk'),
    path('list/', views.view_member, name='member-view'),
    path('<int:pk>/view/', views.view_selected_member, name='member-view-pk'),
    path('ex-members/', views.terminated_members, name='member-terminated'),
]

core/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    return render(request, 'core/index.html')


def dev_guide(request):
    return render(request, 'core/developers-guide.html')

core/templates/core/includes/sidebar.html
{% load static %}
<div class="sidebar flex-shrink-0 w-64 bg-gray-600 shadow">
    <!-- Sidebar content here -->
    <div class="py-4 px-8 flex flex-col justify-between h-full">
        <!-- Your sidebar content goes here -->
        <ul class="space-y-4">
            <li>
                <a href="{% url "core:home" %}"
                   class="block text-white hover:text-black border-2 border-gray-400 rounded px-4 py-1">Home</a>
            </li>
            <li>
                <a href="{% url "member:member-home" %}"
                   class="block text-white hover:text-black border-2 border-gray-400 rounded px-4 py-1">Member</a>
            </li>
            <li>
                <a href="{% url "branch:branch-home" %}"
                   class="block text-white hover:text-black border-2 border-gray-400 rounded px-4 py-1">Branches</a>
            </li>
            <li>
                <a href="{% url "accounts:loan-apply" %}"
                   class="block text-white hover:text-black border-2 border-gray-400 rounded px-4 py-1">Apply
                    for loan</a>
            </li>
            <li>
                <a href="{% url "accounts:cashbook-home" %}"
                   class="block text-white hover:text-black border-2 border-gray-400 rounded px-4 py-1">Manage Funds</a>
            </li>
            <li>
                <a href="{% url "dashboard:dashboard-home" %}"
                   class="block text-white hover:text-black border-2 border-gray-400 rounded px-4 py-1">Dashboard</a>
            </li>


            <!-- Add more sidebar items as needed -->
        </ul>

        <!-- Developer's Guide -->
        <ul class="mt-auto space-y-4">
            <li>
                <a href="#" class="block text-white hover:text-black border-2 border-gray-400 rounded px-4 py-1">User's
                    Guide</a>
            </li>
            <li>
                <a href="{% url "core:dev-guide" %}"
                   class="block text-red-400 hover:text-black border-2 border-gray-400 rounded px-4 py-1">Developer's
                    Guide</a>
            </li>
        </ul>

    </div>

</div>